# Generated by Django 4.0.1 on 2022-01-16 03:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_email_profile_user_id_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('743c6187-587a-4053-b0ef-911096d58a6f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('95467cb8-b3d6-4b2c-a11d-0d8d762a9f68'), primary_key=True, serialize=False, unique=True),
        ),
    ]
