# Generated by Django 4.0.1 on 2022-01-16 03:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('15261acc-158a-4577-9f27-4bc39363892f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('347ba5f3-d48d-403b-a762-0eba562403a2'), primary_key=True, serialize=False, unique=True),
        ),
    ]
