# Generated by Django 4.0.1 on 2022-01-16 03:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_profile_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8165b250-e7b4-47fc-9c2f-7a38cb1fcdaa'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3d1d8b51-aecd-4040-a1b3-0537469e0ee0'), primary_key=True, serialize=False, unique=True),
        ),
    ]
