# Generated by Django 4.0.1 on 2022-01-16 03:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_id_profile_user_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('42a1d417-6adc-4d65-ac0a-9bb5fe36fbee'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2fdfc010-1630-4ed3-8878-8133970cb22e'), primary_key=True, serialize=False, unique=True),
        ),
    ]
