# Generated by Django 4.0.1 on 2022-01-16 10:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_user_profile_user_id_alter_profile_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c6050bab-1701-42a3-bbd6-ada2ce701007'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a41bf55d-c8fb-4174-8dcc-7eca68157fe5'), primary_key=True, serialize=False, unique=True),
        ),
    ]
